### ISSUE TITLE
Route for each clock

### ISSUE THREAD

**Issue by tienvx** [tienvx/angular-clock#24]
/clock/digital for Digital Clock
/clock/analog for Analog Clock
/clock/flipclock for Flip Clock

**Comment by tienvx** [comment]
https://github.com/angular-ui/ui-router
https://github.com/angular-ui/ui-router/wiki/URL-Routing

**Comment by ocditimban** [comment]
http://clock.phuongb.go1.com.vn/#/clock/analog
