### ISSUE TITLE
Create digital clock directive

### ISSUE THREAD

**Issue by tienvx** [tienvx/angular-clock#8]
![digital-clock-jquery-css3](https://cloud.githubusercontent.com/assets/3327643/6650586/230430be-ca4d-11e4-92f1-7ffe433a699b.png)

**Comment by tienvx** [comment]
http://lexxus.github.io/jq-timeTo/

**Comment by tienvx** [comment]
http://www.alessioatzeni.com/wp-content/tutorials/jquery/CSS3-digital-clock/

**Comment by tienvx** [comment]
http://tutorialzine.com/2013/06/digital-clock/

**Comment by tienvx** [comment]
http://www.radoslavdimov.com/jquery-plugins/jquery-plugin-digiclock/

Dual MIT and GPL

**Comment by tienvx** [comment]
http://www.tcpweb.com.br/JS-Clock/

MIT and GPL

**Comment by ocditimban** [comment]
http://clock.phuongb.go1.com.vn/#/clock

**Comment by ocditimban** [comment]
alarm clock http://clock.phuongb.go1.com.vn/#/alarm-clock

**Comment by tienvx** [comment]
https://github.com/soffmodd/Digital-Clock-with-jQuery-and-CSS3
http://www.jqueryscript.net/time-clock/Stylish-jQuery-CSS3-Based-Digital-Clock.html
http://tutorialzine.com/2013/06/digital-clock-adding-alarms/

**Comment by tienvx** [comment]
https://github.com/tienvx/digital-clock
